name: Build ISO

on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Build ISO
        uses: jasonn3/build-container-installer@main
        id: build
        with:
          image_name: bc250
          image_repo: ghcr.io/mygodess
          image_tag: latest
          variant: Kinoite
          version: 43
          iso_name: bc250-43.iso

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: bc250-iso
          path: |
            ${{ steps.build.outputs.iso_path }}
            ${{ steps.build.outputs.iso_path }}.sha256
          retention-days: 7
